import { motion } from 'motion/react';
import { Download, Share2, Printer, RotateCcw, Check } from 'lucide-react';
import { damageItems, projectMeta, calcTotals } from '../data/scope';
import { DamageThumbnail } from '../components/DamagePhotoPair';

interface ClaimPackageScreenProps {
  onRestart: () => void;
}

export default function ClaimPackageScreen({ onRestart }: ClaimPackageScreenProps) {
  const totals = calcTotals();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="min-h-[calc(100vh-3.5rem)] bg-ink-100 py-10"
    >
      <div className="max-w-5xl mx-auto px-6">
        {/* Action bar */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-ink-500 mb-1">
              Claim Package · Ready for Delivery
            </div>
            <h1 className="font-display text-3xl font-bold text-ink-900 leading-tight">
              Your package is ready<span className="text-field-500">.</span>
            </h1>
          </div>

          <div className="flex items-center gap-2">
            <button className="bg-white border border-ink-200 hover:border-ink-900 transition-colors px-4 py-2.5 flex items-center gap-2 font-mono text-xs uppercase tracking-wider">
              <Printer className="w-4 h-4" />
              Print
            </button>
            <button className="bg-white border border-ink-200 hover:border-ink-900 transition-colors px-4 py-2.5 flex items-center gap-2 font-mono text-xs uppercase tracking-wider">
              <Share2 className="w-4 h-4" />
              Share Link
            </button>
            <button className="bg-ink-900 text-ink-50 px-4 py-2.5 flex items-center gap-2 font-mono text-xs uppercase tracking-wider hover:bg-safety-500 hover:text-ink-900 transition-colors">
              <Download className="w-4 h-4" />
              Download PDF
            </button>
            <button
              onClick={onRestart}
              className="ml-4 bg-ink-100 border border-ink-300 hover:bg-ink-200 transition-colors px-4 py-2.5 flex items-center gap-2 font-mono text-xs uppercase tracking-wider"
            >
              <RotateCcw className="w-4 h-4" />
              New Inspection
            </button>
          </div>
        </div>

        {/* PDF-like document preview */}
        <div className="bg-white shadow-xl border border-ink-200">
          {/* Document header */}
          <div className="bg-ink-900 text-ink-50 p-8 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-1/3 h-full bg-safety-500 transform skew-x-12 translate-x-12" />
            <div className="relative flex items-start justify-between">
              <div>
                <div className="font-mono text-[11px] uppercase tracking-[0.3em] text-safety-500 mb-2">
                  Property Loss Inspection Report
                </div>
                <h2 className="font-display text-4xl font-bold leading-tight">
                  {projectMeta.clientName}
                </h2>
                <div className="font-body text-ink-300 mt-1">{projectMeta.address}</div>
              </div>
              <div className="text-right relative z-10">
                <div className="font-mono text-[10px] uppercase tracking-widest text-ink-900 bg-safety-500 inline-block px-2 py-1 mb-3">
                  Generated by FIELDSCOPE.AI
                </div>
                <div className="font-mono text-[11px] uppercase tracking-wider text-ink-900 bg-white/90 p-3 backdrop-blur">
                  <div>Claim: <span className="font-semibold">{projectMeta.claimNumber}</span></div>
                  <div className="mt-1">Report: FS-{projectMeta.claimNumber.slice(-5)}</div>
                </div>
              </div>
            </div>
          </div>

          {/* Meta grid */}
          <div className="grid grid-cols-4 border-b border-ink-200">
            <MetaCell label="Date of Loss" value={projectMeta.dateOfLoss} />
            <MetaCell label="Cause of Loss" value={projectMeta.causeOfLoss} />
            <MetaCell label="Inspected" value={projectMeta.inspectionDate} />
            <MetaCell label="Inspector" value={projectMeta.inspector} accent />
          </div>

          {/* Summary block */}
          <div className="p-8 border-b border-ink-200">
            <div className="grid grid-cols-3 gap-8">
              <div>
                <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-1">
                  Total Items Scoped
                </div>
                <div className="font-display text-4xl font-bold text-ink-900 tabular">
                  {damageItems.length}
                </div>
              </div>
              <div>
                <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-1">
                  Replacement Cost Value
                </div>
                <div className="font-display text-4xl font-bold text-ink-900 tabular">
                  ${totals.total.toLocaleString('en-US', { maximumFractionDigits: 0 })}
                </div>
              </div>
              <div>
                <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-1">
                  Walkthrough Duration
                </div>
                <div className="font-display text-4xl font-bold text-ink-900 tabular">
                  {projectMeta.walkthroughDuration}
                </div>
              </div>
            </div>
          </div>

          {/* Scope narrative */}
          <div className="p-8 border-b border-ink-200">
            <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-3">
              § 01 · Scope Narrative
            </div>
            <div className="font-body text-sm text-ink-800 leading-relaxed space-y-3">
              <p>
                Property sustained significant exterior damage from a severe wind and hail event on April 14, 2026. Field inspection conducted on April 22, 2026 identified {damageItems.length} distinct damage items across the roof envelope, gutters, siding, windows, HVAC, and accessory structures. All items were documented with paired context and detail photography extracted from a continuous 4:18 narrated walkthrough.
              </p>
              <p>
                The primary loss driver is hail impact damage to the roofing system. Both north and south roof slopes exhibit extensive granule displacement and impact bruising consistent with 1-to-1.5-inch hail, with approximately 35 bruises per test square counted — well in excess of the manufacturer's repair threshold. Full roof replacement is recommended on both slopes.
              </p>
              <p>
                Secondary damages include wind-lifted ridge caps, compromised chimney step flashing with evidence of water infiltration requiring interior inspection, hail damage to gutters and downspouts, and impact damage to the south elevation vinyl siding. The HVAC condenser fins have been flattened and require fin-comb repair pending HVAC technician evaluation of coil integrity.
              </p>
            </div>
          </div>

          {/* Photo evidence grid */}
          <div className="p-8 border-b border-ink-200">
            <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-4">
              § 02 · Photographic Evidence
            </div>
            <div className="grid grid-cols-4 gap-3">
              {damageItems.slice(0, 8).map((item) => (
                <div key={item.id} className="group">
                  <DamageThumbnail item={item} />
                  <div className="font-mono text-[9px] uppercase tracking-wider text-ink-500 mt-1.5 truncate">
                    {item.description}
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-4 font-mono text-[10px] text-ink-500 uppercase tracking-wider">
              ↳ Full photo set ({damageItems.length * 2} images) included in appendix
            </div>
          </div>

          {/* Line item breakdown */}
          <div className="p-8 border-b border-ink-200">
            <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-4">
              § 03 · Xactimate Scope
            </div>
            <div className="border border-ink-200">
              <div className="grid grid-cols-[40px_1fr_100px_60px_110px] bg-ink-100 px-4 py-2 font-mono text-[10px] uppercase tracking-wider text-ink-600">
                <div>#</div>
                <div>Description</div>
                <div>Code</div>
                <div className="text-right">Qty</div>
                <div className="text-right">RCV</div>
              </div>
              {damageItems.map((item) => (
                <div
                  key={item.id}
                  className="grid grid-cols-[40px_1fr_100px_60px_110px] px-4 py-2 border-t border-ink-100 items-center"
                >
                  <div className="font-mono text-xs text-ink-500">{item.id}</div>
                  <div className="font-body text-sm text-ink-900">{item.description}</div>
                  <div className="font-mono text-xs font-semibold">{item.xactimateCode}</div>
                  <div className="font-mono text-sm tabular text-right">
                    {item.quantity} {item.unit}
                  </div>
                  <div className="font-mono text-sm font-semibold tabular text-right">
                    ${(item.quantity * (item.unitPrice + item.laborPrice)).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </div>
                </div>
              ))}

              {/* Totals in-document */}
              <div className="bg-ink-50 border-t-2 border-ink-900">
                <div className="grid grid-cols-[1fr_110px] px-4 py-1.5 text-right">
                  <div className="font-body text-sm text-ink-700">Subtotal</div>
                  <div className="font-mono text-sm tabular font-semibold">${totals.subtotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                </div>
                <div className="grid grid-cols-[1fr_110px] px-4 py-1.5 text-right">
                  <div className="font-body text-sm text-ink-700">Overhead + Profit (20%)</div>
                  <div className="font-mono text-sm tabular font-semibold">${(totals.overhead + totals.profit).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                </div>
                <div className="grid grid-cols-[1fr_110px] px-4 py-1.5 text-right">
                  <div className="font-body text-sm text-ink-700">Sales Tax (8.25%)</div>
                  <div className="font-mono text-sm tabular font-semibold">${totals.tax.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                </div>
                <div className="grid grid-cols-[1fr_110px] px-4 py-2.5 text-right bg-ink-900 text-ink-50">
                  <div className="font-display text-base font-bold uppercase tracking-wide">Total RCV</div>
                  <div className="font-display text-lg font-bold tabular">${totals.total.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                </div>
              </div>
            </div>
          </div>

          {/* Certification / sign-off */}
          <div className="p-8 bg-ink-50">
            <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-4">
              § 04 · Inspector Certification
            </div>
            <div className="grid grid-cols-2 gap-8">
              <div>
                <div className="font-body text-sm text-ink-700 leading-relaxed">
                  I certify that the damages described in this report were documented during a physical inspection of the above property on the date indicated. Photographic evidence and narrative observations were captured using FIELDSCOPE.AI mobile capture. Scope items are mapped to Xactimate line codes for adjuster review and pricing.
                </div>
                <div className="mt-6 pt-4 border-t border-ink-300 flex items-center gap-4">
                  <div className="h-10 flex items-end">
                    <div className="font-display italic text-2xl text-ink-900">D. Whitaker</div>
                  </div>
                  <div className="flex-1">
                    <div className="font-mono text-[10px] uppercase tracking-wider text-ink-500">
                      Inspector Signature
                    </div>
                    <div className="font-body text-sm text-ink-900 font-medium mt-0.5">
                      {projectMeta.inspector}
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-3">
                  Package Contents
                </div>
                <ul className="space-y-1.5">
                  {[
                    'Property Loss Inspection Report (this document)',
                    '4:18 walkthrough video (MP4, 2.4 GB)',
                    'Transcript with timestamps (JSON)',
                    '22 damage photos — paired far / close',
                    'Xactimate ESX import file',
                    'Line-item CSV export',
                  ].map((item) => (
                    <li key={item} className="flex items-start gap-2 font-body text-sm text-ink-700">
                      <Check className="w-4 h-4 text-field-500 flex-shrink-0 mt-0.5" strokeWidth={3} />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="px-8 py-4 bg-ink-900 text-ink-400 flex items-center justify-between font-mono text-[10px] uppercase tracking-wider">
            <div>FIELDSCOPE.AI · Generated April 22, 2026 14:32 CST</div>
            <div>Page 1 of 1 · Report ID FS-{projectMeta.claimNumber.slice(-5)}</div>
          </div>
        </div>

        {/* Bottom callout */}
        <div className="mt-8 grid grid-cols-3 gap-4">
          <div className="bg-white border border-ink-200 border-l-4 border-l-field-500 p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest text-field-600 mb-1">
              Adjuster Experience
            </div>
            <div className="font-display text-lg font-bold text-ink-900">
              Zero typing required.
            </div>
            <div className="font-body text-[13px] text-ink-600 mt-1">
              Import the ESX into Xactimate, apply regional pricing, approve.
            </div>
          </div>
          <div className="bg-white border border-ink-200 border-l-4 border-l-safety-500 p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest text-safety-600 mb-1">
              Rep Experience
            </div>
            <div className="font-display text-lg font-bold text-ink-900">
              Walk. Talk. Done.
            </div>
            <div className="font-body text-[13px] text-ink-600 mt-1">
              4 minutes of walkthrough → complete scope package in 24 seconds.
            </div>
          </div>
          <div className="bg-white border border-ink-200 border-l-4 border-l-ink-900 p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest text-ink-600 mb-1">
              Business Impact
            </div>
            <div className="font-display text-lg font-bold text-ink-900">
              4× inspection capacity.
            </div>
            <div className="font-body text-[13px] text-ink-600 mt-1">
              Reps back to next property instead of writing scope in the truck.
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function MetaCell({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className={`
      p-4 border-r border-ink-200 last:border-r-0
      ${accent ? 'bg-safety-500/5' : ''}
    `}>
      <div className="font-mono text-[10px] uppercase tracking-widest text-ink-500 mb-1">
        {label}
      </div>
      <div className="font-body text-sm text-ink-900 font-medium leading-tight">
        {value}
      </div>
    </div>
  );
}
